"""git-bump: bump the SemVer version in a project file and create a git commit+tag.

Public API:
    bump(level, *, file=None, set_version=None, commit=True, dry_run=False) -> str
        level: "patch" | "minor" | "major"
        file: optional explicit path; if None, auto-detect
        set_version: if given, set this version exactly (overrides level)
        commit: whether to create a git commit + tag
        dry_run: if True, print the planned actions but make no changes
        returns the new version string
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

__version__ = "0.1.0"

# A SemVer 2.0.0 production version. Pre-release / build metadata is allowed
# when --set is used but not generated by --major/--minor/--patch.
SEMVER_RE = re.compile(
    r"^(?P<major>0|[1-9]\d*)"
    r"\.(?P<minor>0|[1-9]\d*)"
    r"\.(?P<patch>0|[1-9]\d*)"
    r"(?:-(?P<pre>[0-9A-Za-z.-]+))?"
    r"(?:\+[0-9A-Za-z.-]+)?$"
)

# Recognized file signatures, in detection order. Each entry is:
#   (path, version_regex)
# The version_regex must have exactly one capture group named "v".
_DETECT = [
    ("package.json", re.compile(
        r'(?P<prefix>"version"\s*:\s*")(?P<v>[0-9A-Za-z.\-+]+)(?P<suffix>")'
    )),
    ("pyproject.toml", re.compile(
        r"(?m)^(?P<prefix>version\s*=\s*\")(?P<v>[0-9A-Za-z.\-+]+)(?P<suffix>\")"
    )),
    ("__init__.py", re.compile(
        r'(?m)^(?P<prefix>__version__\s*=\s*["\'])(?P<v>[0-9A-Za-z.\-+]+)(?P<suffix>["\'])'
    )),
    ("VERSION", re.compile(
        r"(?m)^(?P<v>[0-9A-Za-z.\-+]+)$"
    )),
]


def parse_semver(text: str) -> tuple[int, int, int, str | None]:
    """Parse a SemVer 2.0.0 string. Returns (major, minor, patch, prerelease_or_None).

    Raises ValueError on bad input. Pre-release tags are preserved as a string
    so they can be re-attached when bumping (see bump()).
    """
    m = SEMVER_RE.match(text)
    if not m:
        raise ValueError(f"not a valid SemVer 2.0.0 version: {text!r}")
    return int(m.group("major")), int(m.group("minor")), int(m.group("patch")), m.group("pre")


def next_version(current: str, level: str) -> str:
    """Return the next version given a bump level. Drops any pre-release tag."""
    major, minor, patch, pre = parse_semver(current)
    if level == "major":
        return f"{major + 1}.0.0"
    if level == "minor":
        return f"{major}.{minor + 1}.0"
    if level == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"unknown bump level: {level!r} (expected major/minor/patch)")


def detect_file(start: Path = Path(".")) -> tuple[Path, re.Pattern[str]]:
    """Find the first supported version-bearing file. Raises FileNotFoundError."""
    for name, regex in _DETECT:
        path = start / name
        if path.is_file():
            return path, regex
    raise FileNotFoundError(
        "no supported version file found (looked for: "
        + ", ".join(name for name, _ in _DETECT) + ")"
    )


def replace_version(text: str, regex: re.Pattern[str], new_version: str) -> str:
    """Replace the version matched by regex with new_version, preserving everything else.

    The regex must have a "v" group containing the current version. We require
    exactly one match — multi-match ambiguity would be a sign the regex is wrong.
    """
    matches = list(regex.finditer(text))
    if len(matches) == 0:
        raise ValueError("version regex did not match the file content")
    if len(matches) > 1:
        raise ValueError(
            f"version regex matched {len(matches)} times — refusing to guess which one to update"
        )
    m = matches[0]
    return text[: m.start("v")] + new_version + text[m.end("v") :]


def _run_git(*args: str, check: bool = True, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Run a git command. Raises on non-zero exit unless check=False."""
    return subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        check=check,
        cwd=str(cwd) if cwd is not None else None,
    )


def _is_git_repo(cwd: Path | None = None) -> bool:
    try:
        _run_git("rev-parse", "--git-dir", cwd=cwd)
    except subprocess.CalledProcessError:
        return False
    return True


def _tag_exists(tag: str, cwd: Path | None = None) -> bool:
    r = _run_git("rev-parse", "--verify", "--quiet", f"refs/tags/{tag}", check=False, cwd=cwd)
    return r.returncode == 0


def bump(
    level: str,
    *,
    file: str | Path | None = None,
    set_version: str | None = None,
    commit: bool = True,
    dry_run: bool = False,
    cwd: Path | None = None,
) -> str:
    """Compute and write a new version. See module docstring for full semantics.

    Returns the new version string.
    """
    if commit and not _is_git_repo(cwd=cwd):
        raise RuntimeError("not a git repository (or any of the parent directories)")

    start = Path(cwd) if cwd is not None else Path(".")
    if file is not None:
        path = Path(file)
        regex = next((r for n, r in _DETECT if n == path.name), None)
        if regex is None:
            raise ValueError(f"unsupported file: {path.name} (use package.json, pyproject.toml, __init__.py, or VERSION)")
    else:
        path, regex = detect_file(start)

    original = path.read_text(encoding="utf-8")
    m = regex.search(original)
    if m is None:
        raise ValueError(f"could not find a version field in {path}")

    current = m.group("v")
    # The match-regex is intentionally lenient to survive JSON/TOML quoting,
    # but it would happily match a non-SemVer value like 'latest', '0', or 'next'.
    # Validate here so the user gets a clear message instead of a confusing
    # parse_semver error after they picked a bump level.
    parse_semver(current)

    if set_version is not None:
        new = set_version
        # Validate
        parse_semver(new)
    else:
        new = next_version(current, level)

    if new == current:
        raise ValueError(f"version is already {current!r} — nothing to bump")

    if commit and _tag_exists(f"v{new}", cwd=cwd):
        raise ValueError(f"tag v{new} already exists — refusing to overwrite")

    new_text = replace_version(original, regex, new)

    if dry_run:
        print(f"[dry-run] would update {path}: {current} -> {new}", file=sys.stderr)
        if commit:
            print(f"[dry-run] would create commit and tag v{new}", file=sys.stderr)
        return new

    path.write_text(new_text, encoding="utf-8")

    if commit:
        _run_git("add", str(path), cwd=cwd)
        # -m on commit + tag together so the tag and the commit message match.
        _run_git("commit", "-m", f"release: v{new}", cwd=cwd)
        _run_git("tag", "-a", f"v{new}", "-m", f"release v{new}", cwd=cwd)
        print(f"released v{new} (commit + tag created)", file=sys.stderr)
    else:
        print(f"updated {path}: {current} -> {new}", file=sys.stderr)

    return new


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="git-bump",
        description="Bump the SemVer version in a project file and create a git commit+tag.",
    )
    parser.add_argument(
        "level",
        nargs="?",
        choices=("major", "minor", "patch"),
        help="Bump level (ignored if --set is given).",
    )
    parser.add_argument(
        "--set",
        dest="set_version",
        metavar="VERSION",
        help="Set the version to this exact string (must be valid SemVer 2.0.0).",
    )
    parser.add_argument(
        "--file",
        metavar="PATH",
        help="Explicit path to the version file (default: auto-detect package.json / pyproject.toml / __init__.py / VERSION).",
    )
    parser.add_argument(
        "--no-commit",
        action="store_true",
        help="Only write the new version, do not create a git commit or tag.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen but make no changes.",
    )
    parser.add_argument(
        "--cwd",
        metavar="DIR",
        default=None,
        help="Operate on this directory instead of the current working directory "
             "(auto-detection, git commands, and the file write all happen here).",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"git-bump {__version__}",
    )
    args = parser.parse_args(argv)

    if args.set_version is None and args.level is None:
        parser.error("either a bump level (major/minor/patch) or --set VERSION is required")

    cwd = Path(args.cwd) if args.cwd is not None else None
    if cwd is not None and not cwd.is_dir():
        parser.error(f"--cwd path is not a directory: {cwd}")

    try:
        bump(
            args.level,
            file=args.file,
            set_version=args.set_version,
            commit=not args.no_commit,
            dry_run=args.dry_run,
            cwd=cwd,
        )
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        print(f"git {e.cmd[1] if len(e.cmd) > 1 else ''} failed: {e.stderr.strip()}", file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
